version: '3.8'

services:
  frontend:
    build: ./node-app
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: always

  backend:
    build: ./flask-app
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/app_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    restart: always

  db:
    image: postgres:14-alpine   # using official image (simpler & stable)
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./postgres-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
